// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9PT3eBQ7Tm63WC5JZCwItGN0ljNz9VL8',
    appId: '1:154201309435:web:123820cdcdd61cd650f05e',
    messagingSenderId: '154201309435',
    projectId: 'register-c45a5',
    authDomain: 'register-c45a5.firebaseapp.com',
    storageBucket: 'register-c45a5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDup-v9c0nboVAHfS7g1u0LRUENAhDfOBM',
    appId: '1:154201309435:android:e351713999b337e850f05e',
    messagingSenderId: '154201309435',
    projectId: 'register-c45a5',
    storageBucket: 'register-c45a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWRkMOmoPLaVqGxifG9quIHYpCftJanfw',
    appId: '1:154201309435:ios:91362fbf72cf724850f05e',
    messagingSenderId: '154201309435',
    projectId: 'register-c45a5',
    storageBucket: 'register-c45a5.appspot.com',
    androidClientId: '154201309435-te1s4175dkqj1s1pcgutpm4r8kc8oca5.apps.googleusercontent.com',
    iosClientId: '154201309435-slk8401fah5pmaifpefv29604sjvuuam.apps.googleusercontent.com',
    iosBundleId: 'com.example.register',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWRkMOmoPLaVqGxifG9quIHYpCftJanfw',
    appId: '1:154201309435:ios:7992d7a02c4d657c50f05e',
    messagingSenderId: '154201309435',
    projectId: 'register-c45a5',
    storageBucket: 'register-c45a5.appspot.com',
    androidClientId: '154201309435-te1s4175dkqj1s1pcgutpm4r8kc8oca5.apps.googleusercontent.com',
    iosClientId: '154201309435-b2apdljl86j7fv3c6ob1rjgj0apagk8h.apps.googleusercontent.com',
    iosBundleId: 'com.example.register.RunnerTests',
  );
}
