// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2FL81UTjVWqBRO2T3VhOFUSIoYc3Az5U',
    appId: '1:684747738876:web:1364d66708a97374a91179',
    messagingSenderId: '684747738876',
    projectId: 'register-db-1',
    authDomain: 'register-db-1.firebaseapp.com',
    storageBucket: 'register-db-1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDc4_ALb0HKPjErkeyZY54JvOh2iDmWtZU',
    appId: '1:684747738876:android:10b3d79617b95f64a91179',
    messagingSenderId: '684747738876',
    projectId: 'register-db-1',
    storageBucket: 'register-db-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzGyE_cPTwOSxooeYjAcJ27Od5FqfPMwE',
    appId: '1:684747738876:ios:526ed6577002e94ea91179',
    messagingSenderId: '684747738876',
    projectId: 'register-db-1',
    storageBucket: 'register-db-1.appspot.com',
    iosBundleId: 'com.example.register',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzGyE_cPTwOSxooeYjAcJ27Od5FqfPMwE',
    appId: '1:684747738876:ios:94e9ec2a0f96b61da91179',
    messagingSenderId: '684747738876',
    projectId: 'register-db-1',
    storageBucket: 'register-db-1.appspot.com',
    iosBundleId: 'com.example.register.RunnerTests',
  );
}
